services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: traffic-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: traffic-frontend
    restart: always
    ports:
      - "3000:80"